resolver: lts-8.4
packages:
- '.'

extra-deps:
#- BenchmarkHistory-0.0.0.2
- DPutils-0.0.1.0
- OrderedBits-0.0.1.2
- PrimitiveArray-0.8.0.1

flags:
  ADPfusion:
    examples: true
    spectest: false
    debug: false

ghc-options:
#  ADPfusion: -dshow-passes -fllvm -optlo-O3 -keep-llvm-file -optlo-dot-callgraph
#  ADPfusion: -fllvm -optlo-O3

