resolver: lts-5.2
packages:
- '.'

extra-deps:
- BenchmarkHistory-0.0.0.2
- OneTuple-0.2.1
- OrderedBits-0.0.1.0
- PrimitiveArray-0.7.0.1
- tuple-0.3.0.2

flags:
  ADPfusion:
    examples: false
    spectest: false
    debug: false

ghc-options:
#  ADPfusion: -dshow-passes -fllvm -optlo-O3 -keep-llvm-file -optlo-dot-callgraph
#  ADPfusion: -fllvm -optlo-O3

